/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IFa6Solar:fileLinear': typeof import('~icons/fa/6-solar-file-linear')['default']
    IFa6SolarFileLinear: typeof import('~icons/fa/6-solar-file-linear')['default']
    'IFluent:dismiss24Regular': typeof import('~icons/fluent/dismiss24-regular')['default']
    'IFluent:dismiss32Regular': typeof import('~icons/fluent/dismiss32-regular')['default']
    IFluentSpinnerIos20Filled: typeof import('~icons/fluent/spinner-ios20-filled')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoginModal: typeof import('./src/components/Globals/LoginModal/LoginModal.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
