export { default as Controls } from './Controls.vue'
export { default as Cover } from './Cover.vue'
export { default as Info } from './Info.vue'
export { default as MusicBar } from './MusicBar.vue'
export { default as Playlist } from './Playlist.vue'
