/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IFluent:dismiss32Regular': typeof import('~icons/fluent/dismiss32-regular')['default']
    Image: typeof import('./../components/Image.vue')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    Loading: typeof import('./../components/Loading.vue')['default']
    LoginModal: typeof import('./../components/Globals/LoginModal/LoginModal.vue')['default']
    Nav: typeof import('./../components/Nav.vue')['default']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
