/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IFluent:dismiss32Regular': typeof import('~icons/fluent/dismiss32-regular')['default']
    ISolarAltArrowLeftLinear: typeof import('~icons/solar/alt-arrow-left-linear')['default']
    ISolarAltArrowRightLinear: typeof import('~icons/solar/alt-arrow-right-linear')['default']
    ISolarGalleryBoldDuotone: typeof import('~icons/solar/gallery-bold-duotone')['default']
    ISolarMicrophoneBoldDuotone: typeof import('~icons/solar/microphone-bold-duotone')['default']
    ISolarPauseBoldDuotone: typeof import('~icons/solar/pause-bold-duotone')['default']
    ISolarPlayBoldDuotone: typeof import('~icons/solar/play-bold-duotone')['default']
    ISolarSkipNextBoldDuotone: typeof import('~icons/solar/skip-next-bold-duotone')['default']
    ISolarSkipPreviousBoldDuotone: typeof import('~icons/solar/skip-previous-bold-duotone')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    ISolarUserBoldDuotone: typeof import('~icons/solar/user-bold-duotone')['default']
    ISolarUserCircleBoldDuotone: typeof import('~icons/solar/user-circle-bold-duotone')['default']
    ISolarUserBoldDuotone: typeof import('~icons/solar/user-bold-duotone')['default']
    ISolarVinylBoldDuotone: typeof import('~icons/solar/vinyl-bold-duotone')['default']
    ISolarVinylBoldDuotone: typeof import('~icons/solar/vinyl-bold-duotone')['default']
  }
}
