/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IFluent:dismiss32Regular': typeof import('~icons/fluent/dismiss32-regular')['default']
    ISolarGalleryBoldDuotone: typeof import('~icons/solar/gallery-bold-duotone')['default']
    ISolarUnreadLinear: typeof import('~icons/solar/unread-linear')['default']
    ISolarUserCircleBoldDuotone: typeof import('~icons/solar/user-circle-bold-duotone')['default']
    ISolarUserLineDuotone: typeof import('~icons/solar/user-line-duotone')['default']
    ISolarVinylLineDuotone: typeof import('~icons/solar/vinyl-line-duotone')['default']
  }
}
