/** 获取专辑内容 */
export interface ApiAlbum {
    api: '/album'
    method: 'post'
    params: {
        /** 专辑 id */
        id: string
    }
    return: {
        code: number
        album: {
            songs: any[]
            paid: boolean
            onSale: boolean
            mark: number
            awardTags: null
            companyId: number
            blurPicUrl: string
            picUrl: string
            alias: string[]
            artists: {
                img1V1Id: number
                topicPerson: number
                picUrl: string
                alias: string[]
                picId: number
                musicSize: number
                albumSize: number
                briefDesc: string
                img1V1Url: string
                followed: boolean
                trans: string
                name: string
                id: number
                picIdStr?: string
                transNames?: string[]
                img1V1IdStr: string
            }[]
            copyrightId: number
            picId: number
            artist: {
                img1V1Id: number
                topicPerson: number
                picUrl: string
                alias: string[]
                picId: number
                musicSize: number
                albumSize: number
                briefDesc: string
                img1V1Url: string
                followed: boolean
                trans: string
                name: string
                id: number
                picIdStr?: string
                transNames?: string[]
                img1V1IdStr: string
            }
            briefDesc: string
            publishTime: number
            company: string
            commentThreadId: string
            pic: number
            description: string
            tags: string
            status: number
            subType: string
            name: string
            id: number
            type: string
            size: number
            picIdStr: string
            info: {
                commentThread: {
                    id: string
                    resourceInfo: {
                        id: number
                        userId: number
                        name: string
                        imgUrl: string
                        creator: null
                        encodedId: null
                        subTitle: null
                        webUrl: null
                    }
                    resourceType: number
                    commentCount: number
                    likedCount: number
                    shareCount: number
                    hotCount: number
                    latestLikedUsers: null
                    resourceOwnerId: number
                    resourceTitle: string
                    resourceId: number
                }
                latestLikedUsers: null
                liked: boolean
                comments: null
                resourceType: number
                resourceId: number
                commentCount: number
                likedCount: number
                shareCount: number
                threadId: string
            }
        }
        resourceState: boolean
        songs: {
            rtUrls: any[]
            ar: {
                id: number
                name: string
                tns: string[]
                alia: string[]
            }[]
            al: {
                id: number
                name: string
                picUrl: string
                picStr: string
                pic: number
                alia: string[]
            }
            st: number
            noCopyrightRcmd: null
            songJumpInfo: null
            rtype: number
            rurl: null
            pst: number
            alia: string[]
            pop: number
            rt: string
            mst: number
            cp: number
            crbt: null
            cf: string
            dt: number
            h: any
            sq: any
            hr: null
            l: any
            rtUrl: null
            ftype: number
            mv: number
            fee: number
            djId: number
            no: number
            t: number
            v: number
            cd: string
            a: null
            m: any
            name: string
            id: number
            tns?: string[]
            privilege: {
                id: number
                fee: number
                payed: number
                st: number
                pl: number
                dl: number
                sp: number
                cp: number
                subp: number
                cs: boolean
                maxbr: number
                fl: number
                toast: boolean
                flag: number
                preSell: boolean
                playMaxbr: number
                downloadMaxbr: number
                maxBrLevel: string
                playMaxBrLevel: string
                downloadMaxBrLevel: string
                plLevel: string
                dlLevel: string
                flLevel: string
                rscl: null
                freeTrialPrivilege: {
                    resConsumable: boolean
                    userConsumable: boolean
                    listenType: null
                }
                chargeInfoList: {
                    rate: number
                    chargeUrl: null
                    chargeMessage: null
                    chargeType: number
                }[]
            }
        }[]
    }
}
